apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
  labels:
    {{- include "console-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "console-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "console-frontend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "console-frontend.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: console-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
