{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risk-engine.serviceAccountName" . }}
  labels:
    {{- include "risk-engine.labels" . | nindent 4 }}
{{- end }}
