apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: turn
  namespace: {{ include "kit-substation.namespace" . }}
  labels:
    app.kubernetes.io/name: coturn
    {{- include "kit-substation.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 1h
spec:
  to:
    kind: Service
    name: coturn
  port:
    targetPort: turns
  tls:
    termination: passthrough
