apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: {{ include "kit-substation.namespace" . }}
  labels:
    app.kubernetes.io/name: coturn
    {{- include "kit-substation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: coturn
  ports:
    - name: turns
      port: 5349
      targetPort: turns
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coturn
  namespace: {{ include "kit-substation.namespace" . }}
  labels:
    {{- include "kit-substation.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coturn-anyuid
  namespace: {{ include "kit-substation.namespace" . }}
  labels:
    {{- include "kit-substation.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: coturn
    namespace: {{ include "kit-substation.namespace" . }}
