apiVersion: v1
kind: Service
metadata:
  name: dispatch-optimizer
  labels:
    {{- include "dispatch-optimizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dispatch-optimizer.selectorLabels" . | nindent 4 }}
