{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dispatch-optimizer.serviceAccountName" . }}
  labels:
    {{- include "dispatch-optimizer.labels" . | nindent 4 }}
{{- end }}
